### ISSUE TITLE
Create tags

### ISSUE THREAD

**Issue by EchoPouet** [s3pt3mb3r/colorizeEcho#1]
Hello.
Can you create tags for all your version please ? My project isn’t compatible with the last version (master) and I can’t choose a version in my nimble project file without git tags.
Thanks.

**Comment by vxcall** [comment]
Oh, sure!

**Comment by vxcall** [comment]
I think i've done that now.
Does it look fine?
Tell me if u ever have further request

[colorizeEcho/releases](https://github.com/pseuxide/colorizeEcho/releases)

# btw
The last update was fairly simple, so it would be easy to make your project work with latest colorizeEcho if you want to.
I replaced what used to be `colorizeEcho` with `cecho` thats it. function name change for easy use. so u can replace them all in your project to make it compatible.

**Comment by EchoPouet** [comment]
Thank you very much. Tags in git are very important to track release.

In Nim I use [bump](https://nimble.directory/pkg/bump).

Best regards.
